title: Fragmented_Chaos
author: Fragmented_Chaos
lang: zh
email: ""
description: 个人主页 of Fragmented_Chaos，欢迎交流。
baseurl: ""
url: "https://fragmented-chaos.github.io"
github_username: Fragmented-Chaos

# 不加载任何主题，完全自建
markdown: kramdown
plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _sass/custom.scss.bak
